In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 3 데이터셋 로드

In [ ]:
# 기본적인 통계, 분포, 결측치

In [2]:
df = pd.read_csv('data/mental_health_data.csv')
df.shape

(13200, 23)

In [6]:
df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2018,2018,NV,Nevada,BRFSS,Mental Health,At least 14 recent mentally unhealthy days amo...,%,Crude Prevalence,21.6,...,26.8,Overall,Overall,POINT (-117.07184056399967 39.493240390000494),32,MTH,MTH2_0,CRDPREV,OVERALL,OVR
1,2020,2020,NV,Nevada,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Mean,4.1,...,5.8,Race/Ethnicity,"Black, non-Hispanic",POINT (-117.07184056399967 39.493240390000494),32,MTH,MTH1_0,MEAN,RACE,BLK
2,2018,2018,NV,Nevada,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Mean,5.0,...,5.6,Gender,Female,POINT (-117.07184056399967 39.493240390000494),32,MTH,MTH1_0,MEAN,GENDER,GENF
3,2019,2019,NV,Nevada,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,4.7,...,5.2,Overall,Overall,POINT (-117.07184056399967 39.493240390000494),32,MTH,MTH1_0,AGEADJMEAN,OVERALL,OVR
4,2017,2017,NV,Nevada,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Mean,3.5,...,3.9,Overall,Overall,POINT (-117.07184056399967 39.493240390000494),32,MTH,MTH1_0,MEAN,OVERALL,OVR

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13200 entries, 0 to 13199
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   YearStart                  13200 non-null  int64
 1   YearEnd                    13200 non-null  int64
 2   LocationAbbr               13200 non-null  object
 3   LocationDesc               13200 non-null  object
 4   DataSource                 13200 non-null  object
 5   Topic                      13200 non-null  object
 6   Question                   13200 non-null  object
 7   DataValueUnit              13200 non-null  object
 8   DataValueType              13200 non-null  object
 9   DataValue                  10716 non-null  float64
 10  DataValueAlt               10716 non-null  float64
 11  DatavalueFootnote          2561 non-null   object
 12  LowConfidenceLimit         10716 non-null  float64
 13  HighConfidenceLimit        10716 non-null  float64
 14  StratificationCategory1    13200 non-null  object
 15  Stratification1            13200 non-null  object
 16  GeoLocation                13122 non-null  object
 17  LocationID                 13200 non-null  int64
 18  TopicID                    13200 non-null  object
 19  QuestionID                 13200 non-null  object
 20  DataValueTypeID            13200 non-null  object
 21  StratificationCategoryID1  13200 non-null  object
 22  StratificationID1          13200 non-null  object
dtypes: float64(4), int64(3), object(16)
memory usage: 2.3+ MB

In [7]:
# 결측치

df_null=df.isnull()
df_null.head()
# 깨끗

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
df.describe()

,YearStart,YearEnd,DataValue,DataValueAlt,LowConfidenceLimit,HighConfidenceLimit,LocationID
count,13200.000000,13200.000000,10716.00000,10716.00000,10716.000000,10716.000000,13200.000000
mean,2015.979167,2015.979167,6.74804,6.74804,5.244336,8.495502,31.515227
std,3.172196,3.172196,5.47081,5.47081,4.131193,7.545289,18.253692
min,2011.000000,2011.000000,1.20000,1.20000,0.700000,1.800000,1.000000
25%,2013.000000,2013.000000,3.60000,3.60000,3.000000,4.200000,17.000000
50%,2016.000000,2016.000000,4.40000,4.40000,3.700000,5.100000,31.000000
75%,2019.000000,2019.000000,6.40000,6.40000,4.900000,8.700000,45.000000
max,2021.000000,2021.000000,41.20000,41.20000,27.800000,59.400000,78.000000

# 4 학습 예측 데이터셋 만들기

In [13]:
# X : feature  y : label값
df.columns

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'DataValueUnit', 'DataValueType', 'DataValue',
       'DataValueAlt', 'DatavalueFootnote', 'LowConfidenceLimit',
       'HighConfidenceLimit', 'StratificationCategory1', 'Stratification1',
       'GeoLocation', 'LocationID', 'TopicID', 'QuestionID', 'DataValueTypeID',
       'StratificationCategoryID1', 'StratificationID1'],
      dtype='object')

In [16]:
X = df[['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'DataSource',
       'Topic', 'Question', 'DataValueUnit', 'DataValueType', 'DataValue',
       'DataValueAlt', 'DatavalueFootnote', 'LowConfidenceLimit', 'StratificationCategory1', 'Stratification1',
       'GeoLocation', 'LocationID', 'TopicID', 'QuestionID', 'DataValueTypeID',
       'StratificationCategoryID1', 'StratificationID1']]
X.shape

(13200, 22)

In [ ]:
## 'HighConfidenceLimit'

In [18]:
y=df['HighConfidenceLimit']
y.shape

(13200,)

In [19]:
# 사이킷런에서 제공하는 model_selection 의 train_test_split으로 만든다.

from sklearn.model_selection import train_test_split

# train_test_split?
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [22]:
# train 세트의 문제와 정답의 데이터 수를 확인

X_train
# random_state=42 를 지우면 매번 랜덤이 되어서 똑같은 자료를 불러올 수 없으므로 지정

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,DataValueUnit,DataValueType,DataValue,...,LowConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
3958,2013,2013,IL,Illinois,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Mean,3.3,...,3.0,Race/Ethnicity,"White, non-Hispanic",POINT (-88.99771017799969 40.48501028300046),17,MTH,MTH1_0,MEAN,RACE,WHT
2239,2011,2011,DE,Delaware,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,3.4,...,2.0,Race/Ethnicity,Hispanic,POINT (-75.57774116799965 39.008830667000495),10,MTH,MTH1_0,AGEADJMEAN,RACE,HIS
3608,2015,2015,IA,Iowa,BRFSS,Mental Health,At least 14 recent mentally unhealthy days amo...,%,Crude Prevalence,NaN,...,NaN,Race/Ethnicity,Hispanic,POINT (-93.81649055599968 42.46940091300047),19,MTH,MTH2_0,CRDPREV,RACE,HIS
6848,2017,2017,MS,Mississippi,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,5.0,...,4.6,Overall,Overall,POINT (-89.53803082499968 32.745510099000455),28,MTH,MTH1_0,AGEADJMEAN,OVERALL,OVR
6119,2018,2018,MN,Minnesota,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,2.8,...,2.2,Race/Ethnicity,Hispanic,POINT (-94.79420050299967 46.35564873600049),27,MTH,MTH1_0,AGEADJMEAN,RACE,HIS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11964,2018,2018,VI,Virgin Islands,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,NaN,...,NaN,Race/Ethnicity,Hispanic,POINT (-64.896335 18.335765),78,MTH,MTH1_0,AGEADJMEAN,RACE,HIS
5191,2011,2011,MA,Massachusetts,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,2.1,...,1.5,Race/Ethnicity,"Other, non-Hispanic",POINT (-72.08269067499964 42.27687047000046),25,MTH,MTH1_0,AGEADJMEAN,RACE,OTH
5390,2015,2015,MD,Maryland,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Age-adjusted Mean,3.9,...,3.4,Gender,Female,POINT (-76.60926011099963 39.29058096400047),24,MTH,MTH1_0,AGEADJMEAN,GENDER,GENF
860,2014,2014,AR,Arkansas,BRFSS,Mental Health,At least 14 recent mentally unhealthy days amo...,%,Crude Prevalence,NaN,...,NaN,Race/Ethnicity,Hispanic,POINT (-92.27449074299966 34.74865012400045),5,MTH,MTH2_0,CRDPREV,RACE,HIS
7270,2021,2021,ND,North Dakota,BRFSS,Mental Health,Recent mentally unhealthy days among adults ag...,Number,Mean,3.4,...,3.2,Race/Ethnicity,"White, non-Hispanic",POINT (-100.11842104899966 47.47531977900047),38,MTH,MTH1_0,MEAN,RACE,WHT

In [23]:

X_train.shape, y_train.shape

((10560, 22), (10560,))

In [24]:
# test 세트의 문제와 정답의 데이터 수 확인
X_test.shape, y_test.shape

((2640, 22), (2640,))

# 5 GradientBoost

In [27]:
from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()
model

GradientBoostingClassifier()

# 6 학습, 예측

In [28]:
# 학습

model.fit(X_train, y_train)

ValueError: could not convert string to float: 'IL'